server:
  port: 8090
spring:
  profiles:
    active: loadInitialData
  datasource:
    url: "jdbc:h2:mem:testdb"
    driver-class-name: "org.h2.Driver"
    username: "sa"
    password: "password"
  h2:
    console:
      enabled: true
  mail:
    host: "sandbox.smtp.mailtrap.io"
    port: 2525
    username: "7320842c5ff8bb"
    password: "cb31af06ed2f29"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true